spring.application.name=final_project
server.port=8090

spring.config.import=optional:file:.env[.properties]

#db
spring.datasource.driver-class-name=${DB_DRIVER}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#jwt
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=6
jwt.header=Authorization
jwt.token-prefix=Bearer




#포스트맨 경로 요청 오류 찾으려고 디버그 단위로 로그 확인함
#logging.level.org.springframework.security=DEBUG

# 구글 Auth 관련
spring.security.oauth2.client.registration.google.client-id=${CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile


#smtp (???)
# 구글 콘솔의 승인된 리다이렉션 URI와 반드시 일치해야 함!
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI}

# 메일 설정 관련
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.debug=true

#????? port ???? ??
app.frontend-url=http://localhost:3000


#jwt ?? -> ??? redirect? ? ?? (false->????, true->??)
cookie.secure=false

#파일 관련
file.upload.path=${FILE_UPLOAD_PATH}
