spring.application.name=final_project
server.port=8090

#db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://database-1.cryemckcq0cw.ap-northeast-2.rds.amazonaws.com:5432/postgres
spring.datasource.username=admin1
spring.datasource.password=admin1234

#jwt
jwt.secret=Z5yJznyhsGAsBX5MBvTPEQgUPJXZ9dxfR0HPgSiXBsqZLiUNBDk5zc0aMemluvyR
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=6
jwt.header=Authorization
jwt.token-prefix=Bearer




#???? ?? ?? ?? ???? ??? ??? ?? ???
#logging.level.org.springframework.security=DEBUG

# ?? Auth ??
spring.security.oauth2.client.registration.google.client-id=788984888252-3r5gnorvksu82aie6bjqc2b06h5gm2o2.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=RoMkSWtQ3KHAox7ZLWW5NR_y2cd
spring.security.oauth2.client.registration.google.scope=email,profile


#smtp (???)
# ?? ??? ??? ????? URI? ??? ???? ?!
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8090/login/oauth2/code/google

# ?? ?? ??
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=giveandtoken@gmail.com
spring.mail.password=aznextcxyycgeytr

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.debug=true

#????? port ???? ??
app.frontend-url=http://localhost:3000


#jwt ?? -> ??? redirect? ? ?? (false->????, true->??)
cookie.secure=false

#?? ??
file.upload.path=c:/upload

blockchain.rpc.url=https://polygon-mainnet.g.alchemy.com/v2/WGr48mvmPmzhjXv20aFaY
blockchain.gas.price=30000000000
blockchain.gas.limit=6000000
blockchain.contract.donation-token-address=0x5ed5660830b7A0F2eca908bB7759823f8E73b7e2
blockchain.wallet.hot-address=0x68a498a44468cB991Cde892dcDE9e073D706BA6D
