package com.merge.final_project.notification.inapp;

public enum NotificationType {
    FOUNDATION_APPROVED,
    FOUNDATION_REJECTED,
    CAMPAIGN_APPROVED,
    CAMPAIGN_REJECTED,
    FINAL_REPORT_APPROVED,
    FINAL_REPORT_REJECTED,
    FINAL_REPORT_DUE_WARNING,
    FINAL_REPORT_OVERDUE,
    ACCOUNT_DISABLED,
    ACCOUNT_ENABLED,
    SETTLEMENT_COMPLETED
}
